# SPDX-FileCopyrightText: 2024 Tomodachi94
#
# SPDX-License-Identifier: MIT

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "ts-types"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gitsubmodule"
    directory: "vendor"
    schedule:
      interval: "weekly"