#!/usr/bin/env just --justfile

default: lint

install:
	npm ci

lint: install
	npx eslint .

publsh-npm: install
	npm publish \
		--provenance \
		--ignore-scripts \
		--access public

publish-jsr: install
	npm exec -- jsr publish \
		--allow-slow-types # tstl needs ambient types
