#!/usr/bin/env just --justfile

default: lint

install:
	npm install --save-dev --silent

lint: install
	npx eslint .

copy-readme:
	cp ../docs/tstl-types.md ./README.md

publish: install copy-readme
	npm exec -- jsr publish \
		--allow-slow-types # tstl needs ambient types
