#!/usr/bin/env just --justfile

default: lint

install:
	npm install --save-dev --silent

lint: install
	npx eslint .

publish: install
	npm exec -- jsr publish \
		--allow-slow-types # tstl needs ambient types
