package.path = "/lib/?.lua;/lib/?;/lib/?/init.lua;" .. package.path

describe("util", function()
	it("require('unicorn.util') returns a table", function()
		expect(require("unicorn.util")):type("table")
	end)
	it("smartHttp fails with a bad status code", function()
		local unicornUtil = require("unicorn.util")
		expect.error(unicornUtil.smartHttp, "https://httpbin.io/status/404")
	end)
	it("smartHttp succeeds with a good status code", function()
		local unicornUtil = require("unicorn.util")
		unicornUtil.smartHttp("https://example.com")
	end)
	it("evaluateInSandbox can evaluate a simple Lua string", function()
		local unicornUtil = require("unicorn.util")
		local thisFunction = unicornUtil.evaluateInSandbox("return 1")
		expect(thisFunction):type("function")
		expect(thisFunction()):equals(1)
	end)
	it("evaluateInSandbox fails to evaluate Lua with unauthorized functions", function()
		local unicornUtil = require("unicorn.util")
		expect.error(unicornUtil.evaluateInSandbox("fs.list('/')"))
	end)
	it("substituteInPlace replaces the contents of a file", function()
		local unicornUtil = require("unicorn.util")
		unicornUtil.fileWrite("return 1", "/lib/substituteInPlace-replaces.lua")
		unicornUtil.substituteInPlace("/lib/substituteInPlace-replaces.lua", "1", "2")
		expect(require("substituteInPlace-replaces")):equals(2)
		fs.delete("/lib/substituteInPlace-replaces.lua")
	end)
end)
