---Generate a binary wrapper, which is effectively a symlink for a Lua executable program.
---@param pathWithArgs string "The path to wrap, including any command-line arguments."
---@param desiredPath string "A path."
local function makeBinWrapper(pathWithArgs, desiredPath)
	if fs.exists(path) and not fs.exists(desiredPath) then
		local desiredPath = fs.open(desiredPath, "w")
		desiredPath.writeLine("-- !GENERATED by makeBinWrapper")
		desiredPath.writeLine(string.format("shell.run('%s')", pathWithArgs))
	else
		printError(string.format("makeBinWrapper: generating a wrapper for '%s' at '%s' failed.", pathWithArgs, desiredPath))
	end
end

local tArgs = {...}

assert(type(tArgs[1]), "string")
makeBinWrapper(tArgs[1])
