name: Publish

on:
  push:
    tags:
      - "ts-types/v**"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
      - run: "nix develop .#"
        name: "Prefetch CI dependencies"
      - run: nix develop .# --command just ts-types/publish
        name: Publish
